version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
        - checkout

        - run:
            name: Integration Test
            command: mvn integration-test

        - run:
            name: Create Test Directory
            command: mkdir -p $CIRCLE_TEST_REPORTS/junit/

        - run:
            name: Peform Unit Tests
            command: find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build