version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

  test:
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
        - checkout

        - run:
            name: Integration Test
            command: mvn integration-test

        # - run:
        #     name: Unit Tests
        #     command: mvn test

        - store_artifacts:
            path: target/surefire-reports

        - store_test_results:
            path: target/surefire-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build